-- Categorie predefinite per il riconoscimento degli esercenti.
-- Il match e' per sottostringa case-insensitive sul nome esercente.

insert into public.default_merchant_categories (keyword, category) values
  ('esselunga', 'Spesa'),
  ('coop', 'Spesa'),
  ('conad', 'Spesa'),
  ('carrefour', 'Spesa'),
  ('lidl', 'Spesa'),
  ('eurospin', 'Spesa'),
  ('penny', 'Spesa'),
  ('md discount', 'Spesa'),
  ('pam ', 'Spesa'),
  ('bennet', 'Spesa'),
  ('iper', 'Spesa'),
  ('crai', 'Spesa'),
  ('despar', 'Spesa'),
  ('trenitalia', 'Trasporti'),
  ('italo', 'Trasporti'),
  ('atm milano', 'Trasporti'),
  ('atac', 'Trasporti'),
  ('gtt', 'Trasporti'),
  ('uber', 'Trasporti'),
  ('freenow', 'Trasporti'),
  ('bolt', 'Trasporti'),
  ('lime', 'Trasporti'),
  ('telepass', 'Trasporti'),
  ('autostrade', 'Trasporti'),
  ('eni', 'Trasporti'),
  ('q8', 'Trasporti'),
  ('esso', 'Trasporti'),
  ('ip ', 'Trasporti'),
  ('tamoil', 'Trasporti'),
  ('ryanair', 'Viaggi'),
  ('easyjet', 'Viaggi'),
  ('wizz air', 'Viaggi'),
  ('ita airways', 'Viaggi'),
  ('booking', 'Viaggi'),
  ('airbnb', 'Viaggi'),
  ('expedia', 'Viaggi'),
  ('trivago', 'Viaggi'),
  ('mcdonald', 'Ristorazione'),
  ('burger king', 'Ristorazione'),
  ('kfc', 'Ristorazione'),
  ('starbucks', 'Ristorazione'),
  ('deliveroo', 'Ristorazione'),
  ('glovo', 'Ristorazione'),
  ('just eat', 'Ristorazione'),
  ('uber eats', 'Ristorazione'),
  ('ristorante', 'Ristorazione'),
  ('pizzeria', 'Ristorazione'),
  ('trattoria', 'Ristorazione'),
  ('osteria', 'Ristorazione'),
  ('caffe', 'Ristorazione'),
  ('farmacia', 'Salute'),
  ('parafarmacia', 'Salute'),
  ('dott', 'Salute'),
  ('poliambulatorio', 'Salute'),
  ('amazon', 'Shopping'),
  ('zalando', 'Shopping'),
  ('zara', 'Shopping'),
  ('h&m', 'Shopping'),
  ('decathlon', 'Shopping'),
  ('mediaworld', 'Shopping'),
  ('unieuro', 'Shopping'),
  ('apple store', 'Shopping'),
  ('ikea', 'Casa'),
  ('leroy merlin', 'Casa'),
  ('brico', 'Casa'),
  ('maisons du monde', 'Casa'),
  ('enel', 'Utenze'),
  ('a2a', 'Utenze'),
  ('hera', 'Utenze'),
  ('iren', 'Utenze'),
  ('tim ', 'Utenze'),
  ('vodafone', 'Utenze'),
  ('windtre', 'Utenze'),
  ('iliad', 'Utenze'),
  ('fastweb', 'Utenze'),
  ('netflix', 'Abbonamenti'),
  ('spotify', 'Abbonamenti'),
  ('disney', 'Abbonamenti'),
  ('dazn', 'Abbonamenti'),
  ('now tv', 'Abbonamenti'),
  ('prime video', 'Abbonamenti'),
  ('apple.com/bill', 'Abbonamenti'),
  ('google', 'Abbonamenti'),
  ('openai', 'Abbonamenti'),
  ('anthropic', 'Abbonamenti'),
  ('notion', 'Abbonamenti'),
  ('adobe', 'Abbonamenti'),
  ('feltrinelli', 'Cultura'),
  ('mondadori', 'Cultura'),
  ('cinema', 'Cultura'),
  ('the space', 'Cultura'),
  ('ticketone', 'Cultura'),
  ('palestra', 'Sport'),
  ('virgin active', 'Sport'),
  ('mcfit', 'Sport'),
  ('anytime fitness', 'Sport')
on conflict (keyword) do nothing;
